import Head from "next/head";
import Image from "next/image";
import Paginator from "../components/Paginator";
import styles from "../styles/Home.module.css";

export default function Home() {
 
  const selectPageCallback = (result) => {
    console.log(result);
  }
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Pagination</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Paginator totalNumberOfItems="61" itemsPerPage="6" selectPageCallback={selectPageCallback}></Paginator>
    </div>
  );
}
